title: たかきの小説ランド
description: お話が読めます。
theme: null

collections:
  works:
    output: true
    permalink: /works/:name/
  chapters:
    output: true
    permalink: /chapters/:name/

defaults:
  - scope:
      path: ""
      type: works
    values:
      layout: work
  - scope:
      path: ""
      type: chapters
    values:
      layout: chapter

markdown: kramdown