title: すずの小説置き場
description: 小説を置いておくためのシンプルな個人サイト
theme: null

collections:
  works:
    output: true
    permalink: /works/:name/
  chapters:
    output: true
    permalink: /chapters/:name/

defaults:
  - scope:
      path: ""
      type: works
    values:
      layout: work
  - scope:
      path: ""
      type: chapters
    values:
      layout: chapter

markdown: kramdown